name: tateel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  video_player: ^2.9.5
  flutter_native_splash: ^2.4.6
  http: ^0.13.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  video_player: ^2.2.18

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/videos/welcome.mp4

  fonts:
    - family: Marhey
      fonts:
        - asset: font/Marhey-Regular.ttf
          weight: 400